#!/usr/bin/env bash

zpool import
cp tank-key /root/.

# Managed by ZFS
#zpool import -R /mnt rpool
#zfs load-key rpool
#zfs mount -a
#zpool import -R /mnt bpool
#zpool import -R /mnt tank
#zfs load-key tank/home
#zfs mount -a

# Managed by NixOS
zpool import -f rpool
zpool import -f tank

zfs load-key -a

mount -t vfat /dev/disk/by-id/nvme-CT1000P5SSD8_20512C054CD8-part1 /nmt/boot

mount -t zfs rpool/crypt/nixos            /mnt
mount -t zfs rpool/crypt/nixos/home       /mnt/home
mount -t zfs rpool/crypt/nixos/etc        /mnt/etc
mount -t zfs rpool/crypt/nixos/nix        /mnt/nix
mount -t zfs rpool/crypt/nixos/var        /mnt/var
mount -t zfs rpool/crypt/nixos/var/tmp    /mnt/var/tmp
mount -t zfs rpool/crypt/nixos/var/cache  /mnt/var/cache
mount -t zfs tank/media                   /mnt/media
