#!/usr/bin/env bash

source disks

####
# disks
########################
echo "Partitioning root disk"
sgdisk -a1 -n1:24K:+1000K -t1:EF02 $ROOT_DISK
sgdisk     -n2:1M:+512M   -t2:EF00 $ROOT_DISK
sgdisk     -n3:0:+1G      -t3:BF01 $ROOT_DISK
sgdisk     -n4:0:0        -t4:8300 $ROOT_DISK

sleep 2

mkdosfs -F 32 -s 1 -n EFI ${ROOT_DISK}-part2

####
# rpool
########################
echo "Creating encrypted rpool."

zpool create -f              \
  -o altroot=/mnt            \
  -o ashift=12               \
  -O normalization=formD     \
  -O atime=off               \
  -O acltype=posixacl        \
  -O compression=lz4         \
  -O mountpoint=none         \
  -O canmount=off            \
  rpool ${ROOT_DISK}-part4

zfs create -o com.sun:auto-snapshot=false                                      \
           -o canmount=off                                                     \
           -o encryption=aes-256-gcm                                           \
           -o keyformat=passphrase                                             \
           -o keylocation=prompt                          -o mountpoint=none   rpool/crypt
zfs create -o com.sun:auto-snapshot=false                 -o mountpoint=legacy rpool/crypt/nixos
zfs create -o com.sun:auto-snapshot=true                  -o mountpoint=legacy rpool/crypt/nixos/home
zfs create -o com.sun:auto-snapshot=true                  -o mountpoint=legacy rpool/crypt/nixos/etc
zfs create -o com.sun:auto-snapshot=false                 -o mountpoint=legacy rpool/crypt/nixos/nix
zfs create -o com.sun:auto-snapshot=true                  -o mountpoint=legacy rpool/crypt/nixos/var
zfs create -o com.sun:auto-snapshot=false -o setuid=off   -o mountpoint=legacy rpool/crypt/nixos/var/tmp
zfs create -o com.sun:auto-snapshot=false                 -o mountpoint=legacy rpool/crypt/nixos/var/cache

zpool set bootfs=rpool/crypt/nixos rpool

mkdir /mnt
mount -t zfs rpool/crypt/nixos            /mnt

mkdir /mnt/etc
mkdir /mnt/nix
mkdir /mnt/var
mount -t zfs rpool/crypt/nixos/etc       /mnt/etc
mount -t zfs rpool/crypt/nixos/nix       /mnt/nix
mount -t zfs rpool/crypt/nixos/var       /mnt/var

mkdir /mnt/var/cache
mkdir /mnt/var/tmp
mount -t zfs rpool/crypt/nixos/var/cache /mnt/var/cache
mount -t zfs rpool/crypt/nixos/var/tmp   /mnt/var/tmp

####
# tank
########################
echo "Creating tank"

mkdir /mnt/root

cp tank-key /root/tank-key
cp tank-key /mnt/root/tank-key

zpool create -f       \
  -o ashift=12        \
  -o altroot=/mnt     \
  -O atime=on         \
  -O mountpoint=none  \
  -O canmount=off     \
  -O compression=lz4  \
  tank mirror $TANK_DISK_1 $TANK_DISK_2 \
       mirror $TANK_DISK_3 $TANK_DISK_4

zfs create -o com.sun:auto-snapshot=false -o mountpoint=legacy tank/media
zfs create -o com.sun:auto-snapshot=true  \
	   -o atime=off                         \
     -o relatime=on                       \
	   -o encryption=aes-256-gcm            \
     -o keyformat=hex                     \
     -o keylocation=file:///root/tank-key -o mountpoint=legacy tank/home

mkdir /mnt/media
mount -t zfs tank/media /mnt/media

####
# Print results
########################
zfs list -t all -o name,type,mountpoint,compress,exec,setuid,atime,relatime

