#!/usr/bin/env bash

source disks

####
# disks
########################
echo "Partitioning disks"
sgdisk -a1 -n1:24K:+1000K -t1:EF02 $ROOT_DISK_1
sgdisk     -n2:1M:+512M   -t2:EF00 $ROOT_DISK_1
sgdisk     -n3:0:+1G      -t3:BF01 $ROOT_DISK_1
sgdisk     -n4:0:0        -t4:8300 $ROOT_DISK_1

sgdisk -a1 -n1:24K:+1000K -t1:EF02 $ROOT_DISK_2
sgdisk     -n2:1M:+512M   -t2:EF00 $ROOT_DISK_2
sgdisk     -n3:0:+1G      -t3:BF01 $ROOT_DISK_2
sgdisk     -n4:0:0        -t4:8300 $ROOT_DISK_2

sleep 2

# Not using UEFi at the moment, but could be used in the future
mkdosfs -F 32 -s 1 -n EFI ${ROOT_DISK_1}-part2
mkdosfs -F 32 -s 1 -n EFI ${ROOT_DISK_2}-part2

####
# rpool
########################
echo "Creating encrypted rpool."

zpool create -f              \
  -o altroot=/mnt            \
  -o ashift=12               \
  -O normalization=formD     \
  -O atime=off               \
  -O acltype=posixacl        \
  -O compression=lz4         \
  -O mountpoint=none         \
  -O canmount=off            \
  rpool mirror ${ROOT_DISK_1}-part4 ${ROOT_DISK_2}-part4

zfs create -o com.sun:auto-snapshot=false                                      \
           -o canmount=off                                                     \
           -o encryption=aes-256-gcm                                           \
           -o keyformat=passphrase                                             \
           -o keylocation=prompt                          -o mountpoint=none   rpool/ROOT
zfs create -o com.sun:auto-snapshot=false                 -o mountpoint=legacy rpool/ROOT/nixos
zfs create -o com.sun:auto-snapshot=true                  -o mountpoint=legacy rpool/ROOT/nixos/etc         
zfs create -o com.sun:auto-snapshot=true                  -o mountpoint=legacy rpool/ROOT/nixos/var         
zfs create -o com.sun:auto-snapshot=false                 -o mountpoint=legacy rpool/ROOT/nixos/var/cache   
zfs create -o com.sun:auto-snapshot=false -o setuid=off   -o mountpoint=legacy rpool/ROOT/nixos/var/tmp     

zpool set bootfs=rpool/ROOT/nixos rpool

mkdir /mnt
mount -t zfs rpool/ROOT/nixos            /mnt

mkdir /mnt/etc
mkdir /mnt/var
mount -t zfs rpool/ROOT/nixos/etc       /mnt/etc
mount -t zfs rpool/ROOT/nixos/var       /mnt/var

mkdir /mnt/var/cache
mkdir /mnt/var/tmp
mount -t zfs rpool/ROOT/nixos/var/cache /mnt/var/cache
mount -t zfs rpool/ROOT/nixos/var/tmp   /mnt/var/tmp

####
# bpool
########################
echo "Creating bpool"

zpool create -o ashift=12 -d \
    -o feature@async_destroy=enabled \
    -o feature@bookmarks=enabled \
    -o feature@embedded_data=enabled \
    -o feature@empty_bpobj=enabled \
    -o feature@enabled_txg=enabled \
    -o feature@extensible_dataset=enabled \
    -o feature@filesystem_limits=enabled \
    -o feature@hole_birth=enabled \
    -o feature@large_blocks=enabled \
    -o feature@lz4_compress=enabled \
    -o feature@spacemap_histogram=enabled \
    -o feature@userobj_accounting=enabled \
    -O acltype=posixacl \
    -O compression=lz4 \
    -O devices=off \
    -O normalization=formD \
    -O relatime=on \
    -O xattr=sa \
    -O mountpoint=none \
    -O canmount=off \
    -o altroot=/mnt \
    bpool mirror ${ROOT_DISK_1}-part3 ${ROOT_DISK_2}-part3

zfs create -o canmount=off -o mountpoint=none   bpool/BOOT
zfs create -o                 mountpoint=legacy bpool/BOOT/nixos

mkdir /mnt/boot
mount -t zfs bpool/BOOT/nixos /mnt/boot

####
# tank
########################
echo "Creating tank"

zpool create -f       \
  -o ashift=12        \
  -o altroot=/mnt     \
  -O atime=on         \
  -O mountpoint=none  \
  -O canmount=off     \
  -O compression=lz4  \
  tank mirror $TANK_DISK_1 $TANK_DISK_2 \
       mirror $TANK_DISK_3 $TANK_DISK_4

zfs create -o com.sun:auto-snapshot=false -o mountpoint=legacy tank/media
zfs create -o com.sun:auto-snapshot=true                       \
	   -o atime=off                                        \
           -o relatime=on                                      \
           -o encryption=aes-256-gcm                           \
           -o keyformat=passphrase                             \
           -o keylocation=prompt          -o mountpoint=legacy tank/home

mkdir /mnt/media
mkdir /mnt/home
mount -t zfs tank/media /mnt/media
mount -t zfs tank/home  /mnt/home

####
# Print results
########################
zfs list -t all -o name,type,mountpoint,compress,exec,setuid,atime,relatime

