#!/usr/bin/env bash

source disks

umount -R /mnt

zpool import
zpool import -f tank
zpool import -f rpool
zpool destroy tank
zpool destroy rpool

rm -rf /mnt

sgdisk --zap-all $ROOT_DISK
sgdisk --zap-all $TANK_DISK_1
sgdisk --zap-all $TANK_DISK_2
sgdisk --zap-all $TANK_DISK_3
sgdisk --zap-all $TANK_DISK_4
